language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - npm run unit

after_script:
  - npm run build
  - cd ./dist
  - git init
  - git config user.name "BarackO"
  - git config user.email "yanghongliu2013@outlook.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GithubToken}@${GH_REF}" master:master
  
env:
 global:
   - GH_REF: github.com/BarackO/Ubuntu.git

